openapi: 3.1.0

info:
  title: Payment Processing and Reporting API
  version: 1.0.0
  description: API for submitting payments and generating reports

paths:
  /payments:
    post:
      summary: Submit a new payment
      operationId: submitPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentSubmission'
      responses:
        '200':
          description: Payment submission successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '422':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /reports:
    post:
      summary: Generate a report
      operationId: generateReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportRequest'
      responses:
        '200':
          description: Report generation successful or no items to generate report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    PaymentSubmission:
      type: object
      required:
        - paymentId
        - userId
        - paymentDate
        - description
        - currency
        - amount
      properties:
        paymentId:
          type: string
        userId:
          type: string
        paymentDate:
          type: string
          format: date
        description:
          type: string
        currency:
          type: string
        amount:
          type: number
          format: float

    ReportRequest:
      type: object
      properties:
        userId:
          type: string
        year:
          type: string
        month:
          type: string

    SuccessResponse:
      type: object
      properties:
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          type: string